### ISSUE TITLE
Add 8086 assembly code example

### ISSUE THREAD

**Issue by ashwinexe** [hackclub/some-assembly-required#13]
- [ ] README.md
- [ ] Hello World

Optionally:
- [ ] Uppercaser

**Comment by jessicard** [comment]
Hi @ashwinexe! I just wanted to check in and see if you were still interested in doing a "Hello World" 8086 program :D

**Comment by jessicard** [comment]
@ashwinexe Closing this for now, but please feel free to open a PR with this if you end up wanting to! :)
