### ISSUE TITLE
Reach out to Chris Sawyer

### ISSUE THREAD

**Issue by maxwofford** [hackclub/some-assembly-required#33]
> even if just to understand why the Rollercoaster Tycoon creator would write 99% of the game in it.
> [To be fair, even after all of this, I still don't understand why they did that.](https://github.com/hackclub/some-assembly-required/blob/1a701f1dd9b9f828b0e14e9600ffa432f2aa5e04/README.md?plain=1#L10)

Could we reach out to Chris Sawyer and ask him? It'd be awesome to know.

**Comment by maxwofford** [comment]
If anyone is interested in taking this on, I think I found a physical mailing address we can send letters to his company. No email addresses I could find.

**Comment by bellesea** [comment]
> If anyone is interested in taking this on, I think I found a physical mailing address we can send letters to his company. No email addresses I could find.

Omg yes please! @quackduck would you be interested in working together on this? I can draft the letter w/ you and you can physically send it from HQ?

**Comment by quackduck** [comment]
Sure!

**Comment by jessicard** [comment]
@bellesea @quackduck Just wanted to check in and see if this was still on the map or not! If so let's leave it open, but if not we can go ahead and close it for now :)

**Comment by bellesea** [comment]
@jessicard ahhh thank you for the reminder haha! It's def still on the map but not currently being prioritized so we can close it?
