### ISSUE TITLE
Better RISC-V section

### ISSUE THREAD

**Issue by TheThirdOne** [hackclub/some-assembly-required#37]
Hi, I saw this repo on HN and after a look around saw the RISC-V code sample. As the maintainer of [RARS](https://github.com/TheThirdOne/rars), I wanted to reach out as a resource. I don't really want to write anything, but if someone wants to expand the RISC-V section I would be willing to answer questions / offer advice.

If the RISC-V section is not going to be expanded at all, I would recommend two changes:

 1. [Venus](https://venus.cs61c.org/) should be linked to instead of the Cornell simulator. The Cornell simulator does not warn / error when you write invalid code like `addi t0, t0, 0x1000` which makes it harder to learn. 

 2. The note column should be cropped of of the instruction table; it is factually incorrect and misleading. Nearly all of the instructions with immediates are msb extended. However it doesn't even make sense to talk about `sltu` as extending anything. The note only makes sense for `lbu` and `lhu`, but even in those cases only occurs for the loaded data and not the offset immediate which is msb extended.

**Comment by bellesea** [comment]
Hiii @TheThirdOne Thank you for the offer and reaching out! Woah, RARS is so cool and easy to set up! Do you have suggestions for key things the RISC-V section should expand on or include?

On changes:
1. ooo this looks amazing! we'll make the swap, thank you :)
2. ahhh thank you for pointing that out! As i'm contributing to the guide, i'm also learning and i'm a slightly confused by what `msb extended` means... does it mean adding more binary digits to the data w/o changing sign or value? Would you be willing to share a resource where i can learn more about this?

Thank you so so much and have an amazing day!

**Comment by TheThirdOne** [comment]
> Do you have suggestions for key things the RISC-V section should expand on or include?

I don't have any particular ideas. I haven't been involved in teaching people assembly so I don't have a good idea of when to teach each bit of information.

"MSB extended" stands for Most Significant Bit extended. It is more often called Sign extended and your description is quite accurate. https://en.wikipedia.org/wiki/Sign_extension

**Comment by bellesea** [comment]
@TheThirdOne Thank you! Ahhh that's cool hehe, will close this issue w/ a commit for your suggested changes. Will keep your offer in mind if we do expand on the RISC-V section, thank you so much! 

> "MSB extended" stands for Most Significant Bit extended. It is more often called Sign extended and your description is quite accurate. https://en.wikipedia.org/wiki/Sign_extension
Oooo, got it :) Thanks!

Have an awesome weekend!
