### ISSUE TITLE
Loop de Loop polish required

### ISSUE THREAD

**Issue by darkgray1981** [hackclub/some-assembly-required#41]
The assembly code in the **Loop de Loop** chapter could use another look:
`mul rcx, rax       ; multiply our result by our base, save into rcx`
This should probably be using _rbx_, since that's the designated base, not _rax_, which is the exponent.

And in the explanation just above, there's a 8\*2 step missing, while this one is incorrect:
`4. result = 16 * 2, result is now 16`
Since 16\*2 is not 16.

**Comment by jessicard** [comment]
Thanks for making this issue after chatting on HN, really appreciate you catching this!

> The assembly code in the **Loop de Loop** chapter could use another look:
> `mul rcx, rax       ; multiply our result by our base, save into rcx`
> This should probably be using _rbx_, since that's the designated base, not _rax_, which is the exponent.

Fixed in f7b0ef788710e1a9e072b7cc920040d07814906b.

> And in the explanation just above, there's a 8\*2 step missing, while this one is incorrect:
> `4. result = 16 * 2, result is now 16`
> Since 16\*2 is not 16.

Fixed by @jodal in #46.
