### ISSUE TITLE
Typo in conditionals.md

### ISSUE THREAD

**Issue by m3rcurial** [hackclub/some-assembly-required#43]
For our conditional jump, we are using ```jl```, which stands for "Jump if Less Than". The ```jl``` instruction checks the ```eflags``` register. If ```eflags``` says that the first argument to ```cmp``` was less than the second (```rax < rdi```), it jumps to the specified label. If ```rax >= rbx```, this instruction does nothing.

--------------------

The reference to rdi doesn't make sense to me given the context of the example. My proposed change is:
For our conditional jump, we are using ```jl```, which stands for "Jump if Less Than". The ```jl``` instruction checks the ```eflags``` register. If ```eflags``` says that the first argument to ```cmp``` was less than the second (```rax < rbx```), it jumps to the specified label. If ```rax >= rbx```, this instruction does nothing.

**Comment by jessicard** [comment]
Fixed in https://github.com/hackclub/some-assembly-required/pull/44 :D
