### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by dcbrewster** [hackclub/some-assembly-required#49]
Page: https://github.com/hackclub/some-assembly-required/tree/main/guide/writing-code)/data.md
65 in assembly is 01000001 and not 0010001

Page: some-assembly-required/blob/main/guide/writing-code/registers.md
64-bit registers can hold up to a whopping ...
Should read: 64-bit registers can hold a number up to a whopping ...

**Comment by bellesea** [comment]
Hi @dcbrewster ooo thank you!! would you like to make a PR to fix these typos?
