### ISSUE TITLE
Since $02 is smaller than $03, we get the number/next memory adddress $0203

### ISSUE THREAD

**Issue by ospilos** [hackclub/some-assembly-required#58]
WOOT? This statement is plain misleading and in fact wrong. Please explain in context of endianness and do not use such misleading shortcuts.
Other than that, it is a very nice tutorial, many thanks!

**Comment by jessicard** [comment]
Hi! Could you link to the area you’re referring to?

Thanks so much!

**Comment by ospilos** [comment]
Purrrfect! Many thanks!

**Comment by bellesea** [comment]
Closing this issue as it was fixed with #62 . Thank you for opening this issue :))
