### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by ospilos** [hackclub/some-assembly-required#59]
„Here's another example: At memory location $0040 there is the value #$03 and at memory location $0041there is the value #$02.

STY ($0040)
What do you think this does?“

![Opera Snímek_2022-07-04_190207_skilldrick github io](https://user-images.githubusercontent.com/67208375/177196175-179a739b-2516-495e-b3fe-84c78395b511.png)

— Nothing. The compiler will throw Syntax error.

**Comment by bellesea** [comment]
Hiii @ospilos Thank you so much for pointing this out. My sincerest apologies, I wrote this part of the guide while I was still learning and I was mistaken about how indirect addressing works. In this particular example, the `JMP` instruction should be used instead (it is the only instruction that uses this addressing mode). Will make the changes :))

If you spot any other mistakes, please let us know!

**Comment by ospilos** [comment]
Sure, I will. I really appreciate your effort to fix things. Keep the great work!

**Comment by bellesea** [comment]
Closing this issue as it was fixed with #62. Thank you for highlighting this!
