### ISSUE TITLE
Query regarding contribution.

### ISSUE THREAD

**Issue by amandewatnitrr** [hackclub/some-assembly-required#67]
I have some assembly code on some basic nessecary operations for Intel Microprocssor 8085 and microcontroller 8051 should I make another folder for them or to which folder to commit them into.

**Comment by bellesea** [comment]
Hii @amandewatnitrr woah, that's amazing! Could you please create a folder within the [code folder](https://github.com/hackclub/some-assembly-required/tree/main/code)?

Thank you so much!!!

**Comment by amandewatnitrr** [comment]
Sure @bellesea, will do please look for a recent commit form my side.

**Comment by bellesea** [comment]
Thank you @amandewatnitrr! It looks awesome rn :) Let us know when it's ready to be reviewed :)
